### ISSUE TITLE
Don't make ajax request on loadSession if isSignedIn

### ISSUE THREAD

**Issue by abuiles** [the-refinery/ember-devise-simple-auth#18]
Currently there is a request every time we change routes, what about not doing it if we already have a currentSession?

Is there a reason for making always this request?  Maybe we could handle at a higher level 401, and then try to get the `/session/current`/redirect to sign-in.

**Comment by joefiorini** [comment]
I thought I already added that... hmmm.

**Comment by joefiorini** [comment]
Here it is, this is supposed to do what you want, so there must be an issue there. https://github.com/d-i/ember-devise-simple-auth/blob/master/config/plugin.js#L32-L38

**Comment by joefiorini** [comment]
@abuiles Is this still a problem for you?

**Comment by abuiles** [comment]
@joefiorini not an issue any more, thanks!
