### ISSUE TITLE
Client side validation

### ISSUE THREAD

**Issue by nofxsnap** [the-refinery/ember-devise-simple-auth#20]
What is the recommended way to handle client side validation for login? I added ember-validations to the session model, but it seems to POST to the login URL no matter what.

**Comment by joefiorini** [comment]
Good question. There currently isn't a way. How about for starters I add a validateCrendentials callback where you can return true or false. If false, it will set a property that you can access from a template to display a message. Does that sound good?

**Comment by nofxsnap** [comment]
Yeah, that'd be great!

**Comment by joefiorini** [comment]
This is implemented in the latest release.
