### ISSUE TITLE
"couldn't find file 'ember-devise-simple-auth/globals'" I have this error .

### ISSUE THREAD

**Issue by JeskTop** [the-refinery/ember-devise-simple-auth#23]
I use gem 'ember-devise-simple-auth' and 'ember-rails', I got the `couldn't find file 'ember-devise-simple-auth/globals'` error.

And I try to use the example https://github.com/d-i/ember-devise-simple-auth/tree/master/examples/ember-rails also have this problem. I think something wrong with my operation or the gem bug?

**Comment by jsonMartin** [comment]
Hi Ray,

I don't use bower, so had to install the index.js file manually. I originally got that error as I didn't put it in the /globals subfolder, just in the ember-devise-simple-auth javascript folder and required that in my application.js and got it to work that way.

Hope that helped!

All the best,

Jason

**Comment by JeskTop** [comment]
@jasoncartermartin Thanks.

**Comment by danbartlett** [comment]
I have the same issue. I followed the instructions [here](http://joelencioni.com/blog/2014/01/03/integrating-bower-with-rails/) and now I'm trying to deploy to heroku and keep getting the error:

```
Running: rake assets:precompile
[other assets]
rake aborted!
Sprockets::FileNotFound: couldn't find file 'ember-devise-simple-auth/globals'
```

I've tried moving index.js from out of `globals` into `ember-devise-simple-auth` and updating application.js. Still the same error. Any ideas?
