### ISSUE TITLE
Implementing redirects: export default?

### ISSUE THREAD

**Issue by danbartlett** [the-refinery/ember-devise-simple-auth#31]
I have almost everything set up and working fine - thanks for a great gem! However I am trying to redirect after signin. I added the below to `application.js`, from the docs:

```
export default Ember.Route.extend({
  actions: {
    validSignIn: function() {
      this.transitionTo("compose");
    }
  }
});
```

I tried that but I just get `Uncaught SyntaxError: Unexpected reserved word` I've googled around, and I guess I'm missing some dependency, but to be honest most of what I read about `export module` was beyond me.

I tried adding the same action to `application.js` without the `export default` part and the redirect still doesn't work:

```
Ember.Route.extend({
  actions: {
    validSignIn: function() {
      this.transitionTo("compose");
    }
  }
});
```

Am I missing something obvious?! Any help appreciated.

**Comment by danbartlett** [comment]
Got it working with:

```
App.ApplicationRoute = Ember.Route.extend({
  actions: {
    validSignIn: function() {
      this.transitionTo("compose");
    }
});
```

Should this be clearer in the docs?

**Comment by chiragmongia** [comment]
Hey, this was really helpful. I am getting the same error while using 'import'. Do you have any idea how to use 'import' ?

**Comment by danbartlett** [comment]
Good! Not really, I believe it may be something to do with `ember-cli`? It really should be made a bit clearer.

**Comment by chiragmongia** [comment]
Thanks for your time. 
I am not using ember-cli. I am using 'ember-rails' which sets up the directory structure for Ember on Rails. I am trying to set up ember-simple-auth with devise gem but couldn't use import statement as it raises the error you specified.
It would be great if you help.

**Comment by danbartlett** [comment]
I was using `ember-rails` too - the snippet I posted above was what worked for me.

**Comment by chiragmongia** [comment]
I have referred to the link below-
https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-devise

It has asked to create a controller login.js and put the below code in it.
// app/controllers/login.js
import LoginControllerMixin from 'simple-auth/mixins/login-controller-mixin'

export default Ember.Controller.extend(LoginControllerMixin, {
  authenticator: 'simple-auth-authenticator:devise'
});

I could not use 'import' as it throws an error Uncaught SyntaxError: Unexpected reserved word. Any idea?
